Algoritmo "4_Exercicio"
//  
//  
Var

   raio_area, area ,comprimento_circunferencia, raio_comprimento: real



Inicio
   escreva("entre com o valor do raio da circunferencia: ")
   leia(raio_area)
   area<-(3.14159*raio_area^2)
   escreval("o valor da area da circunferencia é: ", area)
   escreval("entre com o valor do raio da circunferencia: ")
   leia(raio_comprimento)
   comprimento_circunferencia<-(2*3.14159*raio_comprimento)
   escreval("o comprimento da circunferencia é: ",comprimento_circunferencia)
   
   

Fimalgoritmo